# SPDX-FileCopyrightText: 2024 KindSpells Labs S.L.
#
# SPDX-License-Identifier: MIT

name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    strategy:
      matrix:
        node-version: [22]
        os: [ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository # v4.1.1
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Install PNPM # v3.0.0
      uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d
      with:
        version: '9.12.0'
    - name: Use Node.js ${{ matrix.node-version }} # v4.0.2
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Publish to NPM registry
      run: pnpm publish --provenance --no-git-checks --access public
      working-directory: ./@kindspells/astro-shield
      env:
        NPM_CONFIG_PROVENANCE: 'true'
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
