# SPDX-FileCopyrightText: 2024 KindSpells Labs S.L.
#
# SPDX-License-Identifier: MIT

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main]

defaults:
  run:
    working-directory: .

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 18, 20 ]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository # v4.1.1
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      with:
        fetch-depth: 0
    - name: Install PNPM # v3.0.0
      uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d
      with:
        version: '8.15.4'
    - name: Use Node.js ${{ matrix.node-version }} # v4.0.2
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Run Moon CI checks
      run: pnpm moon ci
      env:
        MOONBASE_SECRET_KEY: ${{ secrets.MOONBASE_SECRET_KEY }}
